/**
 * Builds the auxiliary prompt that the running agent (or the model) uses to
 * refine a deterministic scaffold into a fully-complete plan.md / AGENTS.md.
 */
import type { RepoFacts } from "./repo";
import type { Template } from "./templates";
import { PLUGIN_NAME } from "./constants";

export function buildAgentsRefineInstruction(
  _cwd: string,
  _facts: RepoFacts,
  _template: Template,
): string {
  return [
    `Refine the AGENTS.md for the project at "${_cwd}".`,
    "",
    "A deterministic scaffold has already been written to AGENTS.md using the project template.",
    "Complete it with real project knowledge. Keep the template's section structure. Do not invent",
    "commands that are not verifiable — run the project's tools to confirm before writing them.",
    "",
    "Focus on replacing the remaining TODO placeholders:",
    "- Project Summary: 2-5 sentences (what it does, who uses it, main language/runtime, domain constraints).",
    "- Repository Layout: the actual top-level structure.",
    "- Development Commands: verified setup/build/test/lint/format/run (or 'Not available').",
    "- Special Constraints: security, performance, compatibility, data, deployment, or domain constraints.",
    "",
    "Focus on replacing the remaining TODO placeholders:",
    "- Project Summary: 2-5 sentences (what it does, who uses it, main language/runtime, domain constraints).",
    "- Repository Layout: the actual top-level structure.",
    "- Development Commands: verified setup/build/test/lint/format/run (or 'Not available').",
    "- Special Constraints: security, performance, compatibility, data, deployment, or domain constraints.",
    "",
    "Use the Working Rules, Implementation Rules, Testing, and Documentation sections from the template.",
    "After editing, read AGENTS.md back and confirm no 'TODO'/'TBD'/'FIXME' placeholders remain.",
    `Author this file by editing AGENTS.md. This is generated by ${PLUGIN_NAME}.`,
  ].join("\n");
}

export function buildPlanRefinementInstruction(
  cwd: string,
  _template: Template,
): string {
  return [
    `Refine plan.md for the project at "${cwd}".`,
    "",
    "A deterministic scaffold was written at plan.md. plan.md is a private implementation",
    "ledger for the current task — keep it concise, current, and specific. Do not invent commands;",
    "confirm them against the project before writing.",
    "",
    "Fill the remaining placeholders:",
    "- Goal: the concrete final outcome of the current task.",
    "- Scope in/out boundaries.",
    "- Constraints (preserve public behavior, small reviewable changes, no new deps unless justified).",
    "- Current State: relevant files, existing behavior, known commands, risks.",
    "- Acceptance Criteria and a Test Plan (narrowest check first).",
    "- Phases 0-2: orientation, implementation, validation — set status/summary/deviation.",
    "",
    "After editing, read plan.md back and confirm no 'TODO'/'TBD'/'FIXME' placeholders remain.",
    `Author: "plan.md" via ${PLUGIN_NAME}.`,
  ].join("\n");
}
